# -*- coding: utf-8 -*-
"""listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZ87GR3E23h3RNcWsklECRcLnnFyW0bq
"""

# Exercico 1
lista = [1,2,3,4,5,6,7,8,9,10]
print(lista)

# Exercico 2

lista = ['chocolate', 'banana', 'abacaxi', 'uva', 'morango'  ]
print(lista)

# Exercico 3

frase1 = 'Se beber'
frase2 = 'não dirija!'
frase_final = frase1 + frase2 
print(frase_final)

# Exercico 4


tuple1 = (1,2,2,3,4,4,4,5)
tuple1.count(4)


dict3 ={}
print(dict3)

dict = {'K1':'martelo', 'K2': 'serrote', 'K3':'machado' }
print(dict)


dict['K4'] = 'parafuso'
print(dict)