# -*- coding: utf-8 -*-
"""slide1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xG1l4STs2oTvaGUV1m3FkcFyjlAeEPe1

**VARIÁVEIS E TIPOS BÁSICOS DE DADOS EM PYTHON**

Variáveis são espaços alocados na memória RAM para guardar valores temporariamente. Em Python, esses espaços não precisam ser tipados, ou seja, a variável pode ser alocada sem especificar o tipo de dado que ela aguardará. O interpretador Python é capaz de determinar o tipo de dado da variável com base no seu valor, ou seja, as variáveis são tipadas dinamicamente nessa linguagem.
"""

x = 10
nome = 'aluno'
nota = 8.75
fez_inscricao = True

"""Para saber o tipo de dado que uma variável guarda, podemos imprimir seu tipo usando a função type() , veja como:"""

print(type(x))
print(type(nome))
print(type(nota))
print(type(fez_inscricao))

nome = input("Digite um nome: ")
print(nome)

# Modo 1 - usando formatadores de caracteres (igual na linguagem C) para imprimir variável e texto
print("Olá %s, bem vindo a disciplina de programação. Parabéns pelo seu primeiro hello world" % (nome))

# Modo 2 - usando a função format() para imprimir variável e texto
print("Olá {}, bem vindo a disciplina de programação. Parabéns pelo seu primeiro hello world".format(nome))

# Modo 3 - usando strings formatadas
print(f"Olá {nome}, bem vindo a disciplina de programação. Parabéns pelo seu primeiro hello world")